### PR TITLE
Update SVG tag names + Support first-letter-uppercase HTML tags

### PR DESCRIPTION
**Pull request by kynikos**
Hi, I've noticed that the SVG tag names weren't tested, and they were actually unsynchronized against [svg-tag-names](https://github.com/wooorm/svg-tag-names), so I've patched them and added a test, similar to what is already done for HTML tags, which are tested against [html-tag-names](https://github.com/wooorm/html-tag-names).

Then I've also bundled 4f54e6a to add native support for using HTML tags case-insensitively, since for example I prefer starting them with a capital letter to avoid conflicts with other variables in the code, e.g. `{ Div } = require('hyperscript-helpers')(h);`. Also, at least `var` is a reserved JS keyword, so this patch allows using e.g. `Var()`.

### CODE REVIEW

**Comment by ohanhi** [comment]
Cool, this seems great. Thanks for your efforts (also for the Proxy implementation even if we can't take that into use yet)!

**Comment by kynikos** [comment]
Thank you for reviewing this :) Would you also merge an additional commit that mentions the additional tag spelling in the README if I push it?

About the Proxy implementation in #45, I closed the PR, but do you think it's worth to be reopened in case that solution is useful for those who are targeting only ES6 browsers?

**Comment by ohanhi** [comment]
@kynikos Yeah, a mention in the readme would be great.

I think the Proxy version could be a separate npm package. You can fork the repository and publish it yourself, if you'd like.

**Comment by kynikos** [comment]
Cheers, I've just pushed an update to the readme then, also documenting `createTag()` while I was at it, and I've added a couple of tests for the uppercase spelling.

**Pull request merged**
